pipeline {
  agent any

  environment {
    SERVICE_NAME = "notification-service"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install dependencies') {
      steps {
        sh 'npm install'
      }
    }

    stage('Run tests') {
      steps {
        sh 'npm run test'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t $SERVICE_NAME .'
      }
    }

  }
}