services:
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "${KAFKA_BROKER_PORT}:9092"
      - "${KAFKA_LOCALHOST_PORT}:29092"

    env_file:
      - .env

    environment:
      KAFKA_NODE_ID: ${KAFKA_NODE_ID}
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_NODE_ID}@kafka:${KAFKA_CONTROLLER_PORT}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:${KAFKA_CONTROLLER_PORT}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: ${CLUSTER_ID}

    volumes:
      - kafka_data:/var/lib/kafka/data
      - ./scripts:/scripts

    networks:
      - it-job-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

    depends_on:
      - kafka

    networks:
      - it-job-network

  kafka-init:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - kafka
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/bin/bash", "/scripts/create-topics.sh"]

    networks:
      - it-job-network

volumes:
  kafka_data:

networks:
  it-job-network:
    external: true